### ISSUE TITLE
“Setting up your system” - change min version to 3.10

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#196]
Also motivate this choice. See also #142.

**Comment by TheErk** [comment]
I insist on that.
You should not require a too "high" version of CMake for most of the recipe.
If you need 3.10 for some recipe then require it only for those.

Moreover if you require 3.10 for Module file then you can ship up-to-date module files with the recipes and require lower version of CMake itself.

You can even do something like:

if (CMAKE_VERSION VERSION_LESS "3.10")
   list(APPEND CMAKE_MODULE_PATH /path/to/local/cmake/Modules)
endif()

since find_package looks in CMAKE_MODULE_PATH first you'll only use
the local version if CMake version is less than the one shipping the appropriate module.

**Comment by bast** [comment]
Thanks for the feedback/hints.

We need to strike a good balance between 1) not being too annoying to non-experts in terms of needing latest dependencies, 2) use modern features to avoid back-porting them and 3) create recipes that will survive some years/months and are not too outdated at print time. And that is not easy.

We will discuss this but I think I agree with you that we should require a very recent version only where we need it.

This could complicate automated testing however but perhaps we can solve it with a testing matrix where we test an off-the-shelf CMake and the latest and greatest on the same set of recipes.

**Comment by TheErk** [comment]
Automated testing could show whether a test/recipe is turned-off because the used version of CMake is too "low". Testing should be OK if all tests runned using a particular version of CMake are ok.

However I do agree that the appropriate version should be chosen so that let's say 90% of the tests ay be run with the lowest required version of CMake. Something like 3.5  should be good (my opinion though).

Like I said in previous comment dragging more up-to-date Module into the source might help as well and perfectly fine. 

If you run 3.10 you'll get the upstream module, if you run 3.5 you'll get the local copy (for FindOpenMP or FindMPI for example).

If you want to find which version got what find the commit that introduce the feature and then lookup
the tags list containing the commit.

For example:
bb032c1bf5 introduced imported target in FindOpenMP.cmake:

You may find that it was introduced in v3.9.0:

Modules (master)$ git tag --contains bb032c1bf5
v3.10.0
v3.10.0-rc1
v3.10.0-rc2
v3.10.0-rc3
v3.10.0-rc4
v3.10.0-rc5
v3.10.1
v3.9.0
v3.9.0-rc1
v3.9.0-rc2
v3.9.0-rc3
v3.9.0-rc4
v3.9.0-rc5
v3.9.0-rc6
v3.9.1
v3.9.2
v3.9.3
v3.9.4
v3.9.5
v3.9.6

**Comment by bast** [comment]
Eric, thanks for the good suggestion. We will follow this strategy.

**Comment by bast** [comment]
I am trying this strategy with FindMPI.cmake and one problem that I see is that this file pulls in a number of other files that it expects in the same path as FindMPI.cmake. E.g.: https://github.com/Kitware/CMake/blob/master/Modules/FindMPI.cmake#L249 etc. etc.

One option would be to have a directory with a lot of files (possibly the entire `Modules/` directory of CMake repo. For the automated testing it will be fine but following the book on a laptop will then be clunky since it will again require to download a tarball and put it in a specific place. Equivalent to installing recent CMake. Am I missing something? What is your view on this?

**Comment by bast** [comment]
Or we really put all the needed files in a subdirectory ("upstream/") for each recipe. Lot of code duplication but since these are read-only files, possibly fine.

**Comment by bast** [comment]
I don't think FindMPI.cmake can be backported this way. Even having all files the code uses syntax that was changed after 3.5 (`NATIVE_COMMAND` in `separate_arguments`). Maybe FindMPI.cmake is an exception but if not I think we have 3 options:
- we do not use features after 3.5 in any recipe (would be conservative but possibly deprecated soon)
- some recipes use features after 3.5, we try to limit those; these recipes fail on 3.5 (and are skipped on CI)
- we raise minimum requirement (not ideal and I agree with Eric's recommendation to not require 3.10)

**Comment by bast** [comment]
After discussing with Roberto we aim at the following:
- For those recipes which now fail with 3.5, we will present both the 3.5 and 3.10 way of doing it
- Very few recipes use completely new functionality and they will only run on 3.10
- Most recipes will run on both
- CI testing will figure out the version and skip respective tests and not complain
- In the book we discuss the 3.10 way of implementing it but under "there is more" also discuss the traditional way

**Comment by bast** [comment]
We have lowered minimum requirement to 3.5. Some recipes then fail but we follow these issues individually until almost everything also works on 3.5. Closing.
