### ISSUE TITLE
Generalize testing

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#244]
The packaging and documentation recipes add targets to the generated build system: `package` and `package_source` for the former, `docs` for the latter. Our testing framework should let us specify which targets to build. Note that although we can do:
```
cmake --build build --target <available_target>
```
we can only list _one target at a time_.

**Comment by bast** [comment]
I am working on this now. This is also connected to #232 which needs a more general testing and more isolated environments.

**Comment by bast** [comment]
I have the following thoughts - please comment:
1. We abandon virtualenv and use pipenv throughout. We can then have a global Pipfile but also local Pipfiles that can shadow the global one.
2. Instead of running all tests inside the big ci_configure_build_test.py, we run individual test.sh in each recipe. The test.sh may then utilize a common test script but one may define a completely different test.sh as well. The advantage of this would be that recipes could run in isolated pipenv/anaconda environments instead of running in one common pipenv. So the only thing that ci_configure_build_test.py would do is glob test.sh scripts and start them, wherever they are.
3. We list targets in menu.yml (such as test, docs, package, package_source). By default only default target is run.
4. We get rid of skip_predicate since we specify all targets explicitly.
5. menu.yml lists the cmake version environment so that we can run 3.5 and 3.10 next to each other.

**Comment by robertodr** [comment]
It sounds wonderful!
