### ISSUE TITLE
Bump minimum requirement to CMake 3.10

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#62]
See https://crascit.com/2016/01/31/enhanced-source-file-handling-with-target_sources/.

- [ ] Document in book
- [ ] Motivate in book
- [x] Update recipe sources on GitHub side
- [ ] Update source snippets that mention 3.0 in the book

**Comment by robertodr** [comment]
Recipe sources updated with #68

**Comment by TheErk** [comment]
I think that requiring 3.10 is too much.
Debian stable (stretch) provides 3.7.2:
https://packages.debian.org/stretch/cmake which will provided 90% of the feature you need for most recipes. I would value the fact that a recipe has a `cmake_minimum_require(...)` corresponding to the required feature. You can even selectively compile/tests recipes depending on the cmake version used by the tester.

**Comment by TheErk** [comment]
Ubuntu latest LTS (xenial) is providing 3.5: https://packages.ubuntu.com/fr/xenial/cmake
Latest Ubuntu (artful or even bionic) is providing 3.9: https://packages.ubuntu.com/fr/artful/cmake
CentOS 7 is providing 3.6: https://centos.pkgs.org/7/epel-x86_64/cmake3-3.6.3-1.el7.x86_64.rpm.html

You will probably dramatically reduce the audience because somebody will have to install 3.10.
and yes I know they can get a tar.gz from Kitware but trust me many people will simply stop trying if this is a strong requirement.

On the other hand if a couple of recipe do require 3.10 and are displayed as disabled because of that then may be people will have already been convinced by the vast majority of the other recipe and go to download/compile 3.10 to continue.

Since I am at it I would NOT require ninja-kitware either. If this particular version is not available then switch to makefile generator. (and display some message about it).

**Comment by bast** [comment]
I fully agree and am working on lowering to 3.5 - I left a note in the book and we follow the lowering to 3.5 in #196. Also agree with the ninja-kitware which we follow in #266. Closing this since it is largely duplicate with #196.
